import bcrypt from 'bcryptjs';

export const DATABASE_NAME = 'e-storefront';

export const COLLECTIONS = {
  users: 'users',
  categories: 'categories',
  products: 'products',
  coupons: 'coupons',
  orders: 'orders',
  reviews: 'reviews',
  addresses: 'addresses',
  tickets: 'tickets',
};

export const hashPassword = (password: string): string => {
  const salt = bcrypt.genSaltSync(10);
  return bcrypt.hashSync(password, salt);
};

export const PASSWORDS = {
  ADMIN: 'Admin@123',
  SELLER: 'Seller@123',
  CUSTOMER: 'User@123',
  SUPPORT: 'Support@123',
};

export const USER_ROLES = {
  ADMIN: 'admin',
  SELLER: 'seller',
  CUSTOMER: 'customer',
  SUPPORT: 'support',
};

export const ID_PREFIX = {
  USER: '65a7b8c9d0e1f2g3h4i5j6k7',
  CATEGORY: '65b7b8c9d0e1f2g3h4i5j6k7',
  PRODUCT: '65c7b8c9d0e1f2g3h4i5j6k7',
  COUPON: '65d7b8c9d0e1f2g3h4i5j6k7',
  ORDER: '65e7b8c9d0e1f2g3h4i5j6k7',
  REVIEW: '65f7b8c9d0e1f2g3h4i5j6k7',
  ADDRESS: '65g7b8c9d0e1f2g3h4i5j6k7',
  TICKET: '65h7b8c9d0e1f2g3h4i5j6k7',
};

export const ORDER_STATUSES = [
  'PENDING',
  'CONFIRMED',
  'PROCESSING',
  'SHIPPED',
  'DELIVERED',
  'CANCELLED',
];
export const PAYMENT_STATUSES = ['PENDING', 'COMPLETED', 'FAILED', 'REFUNDED'];
export const PAYMENT_METHODS = [
  'credit_card',
  'debit_card',
  'paypal',
  'bank_transfer',
  'cash_on_delivery',
];

export const FIRST_NAMES = [
  'James',
  'Mary',
  'Robert',
  'Patricia',
  'John',
  'Jennifer',
  'Michael',
  'Linda',
  'David',
  'Elizabeth',
  'William',
  'Barbara',
  'Richard',
  'Susan',
  'Joseph',
  'Jessica',
  'Thomas',
  'Sarah',
  'Christopher',
  'Karen',
  'Charles',
  'Lisa',
  'Daniel',
  'Nancy',
  'Matthew',
  'Betty',
  'Anthony',
  'Margaret',
  'Mark',
  'Sandra',
  'Donald',
  'Ashley',
  'Steven',
  'Kimberly',
  'Paul',
  'Emily',
  'Andrew',
  'Donna',
  'Joshua',
  'Michelle',
  'Kenneth',
  'Dorothy',
  'Kevin',
  'Carol',
  'Brian',
  'Amanda',
  'George',
  'Melissa',
  'Timothy',
  'Deborah',
];

export const LAST_NAMES = [
  'Smith',
  'Johnson',
  'Williams',
  'Brown',
  'Jones',
  'Garcia',
  'Miller',
  'Davis',
  'Rodriguez',
  'Martinez',
  'Hernandez',
  'Lopez',
  'Gonzalez',
  'Wilson',
  'Anderson',
  'Thomas',
  'Taylor',
  'Moore',
  'Jackson',
  'Martin',
  'Lee',
  'Perez',
  'Thompson',
  'White',
  'Harris',
  'Sanchez',
  'Clark',
  'Ramirez',
  'Lewis',
  'Robinson',
  'Walker',
  'Young',
  'Allen',
  'King',
  'Wright',
  'Scott',
  'Torres',
  'Nguyen',
  'Hill',
  'Flores',
  'Green',
  'Adams',
  'Nelson',
  'Baker',
  'Hall',
  'Rivera',
  'Campbell',
  'Mitchell',
  'Carter',
  'Roberts',
];

export const CITIES = [
  'New York',
  'Los Angeles',
  'Chicago',
  'Houston',
  'Phoenix',
  'Philadelphia',
  'San Antonio',
  'San Diego',
  'Dallas',
  'San Jose',
  'Austin',
  'Jacksonville',
  'Fort Worth',
  'Columbus',
  'Charlotte',
  'Indianapolis',
  'Seattle',
  'Denver',
  'Boston',
  'Nashville',
];

export const STATES = [
  'NY',
  'CA',
  'IL',
  'TX',
  'AZ',
  'PA',
  'TX',
  'CA',
  'TX',
  'CA',
  'TX',
  'FL',
  'TX',
  'OH',
  'NC',
  'IN',
  'WA',
  'CO',
  'MA',
  'TN',
];

export const STREETS = [
  'Main St',
  'Oak Ave',
  'Maple Dr',
  'Cedar Ln',
  'Pine Rd',
  'Elm St',
  'Washington Blvd',
  'Park Ave',
  'Lake Dr',
  'River Rd',
  'Forest Way',
  'Mountain View',
  'Sunset Blvd',
  'Valley Rd',
  'Highland Ave',
];

export const COUPON_CODES = [
  'SAVE10',
  'WELCOME20',
  'FLASH30',
  'SUMMER15',
  'WINTER25',
  'HOLIDAY50',
  'NEWYEAR',
  'FIRSTBUY',
  'LOYALTY10',
  'VIP20',
  'SPECIAL15',
  'DEAL25',
  'MEGA30',
  'SUPER40',
  'ULTRA50',
  'PRIME10',
  'GOLD15',
  'SILVER20',
  'BRONZE25',
  'PLAT30',
];

export const PRODUCTS_NAMES = [
  'Laptop',
  'Mouse',
  'Keyboard',
  'Monitor',
  'Headphones',
  'Speaker',
  'Phone',
  'Tablet',
  'T-Shirt',
  'Jeans',
  'Jacket',
  'Shoes',
  'Hat',
  'Scarf',
  'Boots',
  'Dress',
  'Coffee Maker',
  'Blender',
  'Microwave',
  'Toaster',
  'Vacuum',
  'Dishwasher',
  'Refrigerator',
  'Oven',
];


export const CATEGORIES = [
  {
    name: 'Electronics',
    icon: 'laptop',
    description: 'Electronic devices, gadgets, and equipment',
  },
  { name: 'Clothing', icon: 'shirt', description: 'Apparel and clothing for all occasions' },
  { name: 'Home & Kitchen', icon: 'home', description: 'Home furnishings and kitchen essentials' },
  {
    name: 'Beauty & Personal Care',
    icon: 'sparkles',
    description: 'Beauty products and cosmetics',
  },
  { name: 'Sports & Outdoors', icon: 'trophy', description: 'Sports equipment and outdoor gear' },
  { name: 'Books & Media', icon: 'book', description: 'Books, magazines, and digital media' },
  { name: 'Toys & Games', icon: 'puzzle', description: 'Toys and games for all ages' },
  { name: 'Automotive', icon: 'car', description: 'Auto parts and accessories' },
  { name: 'Garden & Outdoor', icon: 'flower', description: 'Garden tools and outdoor equipment' },
  {
    name: 'Health & Wellness',
    icon: 'heart',
    description: 'Health supplements and wellness products',
  },
  { name: 'Jewelry & Watches', icon: 'gem', description: 'Fine jewelry and watches' },
  { name: 'Pet Supplies', icon: 'paw', description: 'Pet food and accessories' },
  { name: 'Office Supplies', icon: 'briefcase', description: 'Office equipment and supplies' },
  { name: 'Food & Grocery', icon: 'shopping-cart', description: 'Food items and groceries' },
  { name: 'Baby & Kids', icon: 'baby', description: 'Baby products and kids items' },
  { name: 'Furniture', icon: 'couch', description: 'Indoor and outdoor furniture' },
  {
    name: 'Music & Instruments',
    icon: 'music',
    description: 'Musical instruments and accessories',
  },
  { name: 'Art & Crafts', icon: 'palette', description: 'Art supplies and crafting materials' },
  { name: 'Travel & Luggage', icon: 'plane', description: 'Travel gear and luggage' },
  { name: 'Smart Home', icon: 'cpu', description: 'Smart home devices and automation' },
];

export const REVIEW_TITLES = [
  'Excellent product!',
  'Great quality',
  'Highly recommended',
  'Very satisfied',
  'Good value',
  'Amazing!',
  'Perfect fit',
  'Exceeds expectations',
  'Best purchase',
  'Fantastic',
];

export const REVIEW_COMMENTS = [
  'This product exceeded my expectations. Highly recommended!',
  'Excellent quality and fast shipping. Very happy with this purchase.',
  'Great product at a fair price. Will buy again.',
  'Perfect! Exactly what I was looking for.',
  'Amazing quality. Better than expected.',
  'Highly satisfied with this purchase. Great value for money.',
  'This is a fantastic product. Exceeded my expectations.',
  'Excellent! Great quality and very satisfied with my purchase.',
  'Best purchase I have made. Highly recommended to everyone.',
  'Amazing product! Great quality and fast delivery.',
];

export const TICKET_CATEGORIES = [
  'billing',
  'technical',
  'account',
  'shipping',
  'product',
  'return',
  'other',
];
export const TICKET_PRIORITIES = ['low', 'medium', 'high', 'urgent'];
export const TICKET_STATUSES = ['open', 'in-progress', 'pending', 'resolved', 'closed'];
export const TICKET_SUBJECTS = [
  'Issue with order',
  'Payment problem',
  'Account access',
  'Product not as described',
  'Shipping delay',
  'Refund status',
  'Technical support',
  'General inquiry',
];

export const TICKET_DESCRIPTIONS = [
  'I am experiencing an issue with my recent order.',
  'I have a question about my payment method.',
  'I cannot access my account.',
  'The product received is not matching the description.',
  'My order has not arrived yet.',
  'I want to check on my refund status.',
  'I need technical support for using the platform.',
  'General inquiry about your services.',
];

export const TICKET_RESOLUTIONS = [
  'Issue resolved',
  'Refund processed',
  'Account restored',
  'Product replaced',
  'Order expedited',
  'Technical issue fixed',
  'Account updated',
  'Support provided',
];

export const TICKET_COMMENTS = [
  'Thank you for reaching out. We are looking into your issue.',
  'Your refund has been processed and will appear in your account within 3-5 business days.',
  'We have successfully restored your account access.',
  'We are shipping a replacement product to you immediately.',
  'Your order has been expedited and will arrive soon.',
  'The technical issue has been resolved.',
  'Your account information has been updated.',
  'We appreciate your patience. The issue is now resolved.',
];
